;√Ë ˆ—’…´
;-----------------------------------
; Standard 4-bit color definitions
;-----------------------------------
black        EQU 0000b
blue         EQU 0001b
green        EQU 0010b
cyan         EQU 0011b
red          EQU 0100b
magenta      EQU 0101b
brown        EQU 0110b
lightGray    EQU 0111b
gray         EQU 1000b
lightBlue    EQU 1001b
lightGreen   EQU 1010b
lightCyan    EQU 1011b
lightRed     EQU 1100b
lightMagenta EQU 1101b
yellow       EQU 1110b
white        EQU 1111b
